### ISSUE TITLE
Help me, please!

### ISSUE THREAD

**Issue by I7y3o1** [arabacibahadir/sup-res#12]
Help, please, to solve a problem.
Before everything started and worked like clockwork. The last 2 weeks gives an error and I don't know how to overcome it... Perhaps you can tell me how?
![Безымянный](https://user-images.githubusercontent.com/106140747/187095375-c4ffc02f-0864-45e2-a114-ac1d9ca95894.png)

**Comment by arabacibahadir** [comment]
Hey,
I want to help but I can't reproduce this code error. Can you check your library versions? Also, I recommend to install clean virtual environment and try not to update newer library versions.
https://github.com/arabacibahadir/sup-res/blob/master/requirements.txt

`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working`
Probably there is an issue about with 'request' library that uses 'collections' library.
