### ISSUE TITLE
no pinescript ubuntu

### ISSUE THREAD

**Issue by mupsje** [arabacibahadir/sup-res#8]
After running the script,

Pinescript is not showing.

![image](https://user-images.githubusercontent.com/46684538/154869713-fb393e43-8a3d-4c1c-8d59-61d681db4f62.png)

Also "Latest Candlesticks is not showing in chart"
![image](https://user-images.githubusercontent.com/46684538/154869824-1047e4ce-e776-4f13-8c7a-e22c50499e36.png)

I shall install it on Windows tomorrow, let you know.

Thanks again for the great support

**Comment by arabacibahadir** [comment]
I didn't add for low time frames like 1h 4h because of they are not working well in my backtests, in daily and weekly charts are much more accurate for crypto.
If you need pinescript 
`# pinescript_code()` uncomment this code. It gives as a text output pinescript code, you should copy and paste to tradingview.

**Comment by arabacibahadir** [comment]
Also you can try changing sensitivity between 1-3, depends on your needs. Sometimes script gives too much unneccessary lines, for reduce them using 2 or 3 is good. Sometimes sensitivity and binance api cause broke the code. 

https://github.com/arabacibahadir/sup-res/blob/c6fa6a16786107c4e7497dccd0a8136b959913a9/main.py#L155
